version: '3.8'

services:
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'root'
      DATABASE_URL: $DATABASE_URL
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: